apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secp-signaling-service.fullname" . }}
  labels:
    {{- include "secp-signaling-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "secp-signaling-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "secp-signaling-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_ADDR
              value: {{ .Values.env.REDIS_ADDR | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}