# k8s/config/redis-values.yaml
architecture: standalone
auth:
  enabled: true
  password: "redis5666"  # Replace with a secure password
master:
  persistence:
    enabled: true
    storageClass: "ebs-sc"
    size: 8Gi