apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secp-chat.fullname" . }}
  labels:
    {{- include "secp-chat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "secp-chat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "secp-chat.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: REACT_APP_SIGNALING_SERVICE_URL
              value: "ws://secp-signaling-service.secp.svc.cluster.local:8080"
