apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nochat-ingress
  namespace: nochat
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:500532294210:certificate/b2104cc1-1516-4df4-88d3-51962a9eb2b9
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    alb.ingress.kubernetes.io/group.name: "nochat"
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
spec:
  rules:
  - host: nochat.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nochat-web
            port:
              number: 80
      - path: /signaling
        pathType: Prefix
        backend:
          service:
            name: nochat-signaling
            port:
              number: 8080
