apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nochat-ingress
  namespace: nochat
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:500532294210:certificate/b2104cc1-1516-4df4-88d3-51962a9eb2b9
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    alb.ingress.kubernetes.io/group.name: "nochat"
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-group-attributes: >-
      deregistration_delay.timeout_seconds=30,
      stickiness.enabled=true,
      stickiness.type=lb_cookie,
      stickiness.lb_cookie.duration_seconds=86400,
      preserve_client_ip.enabled=true
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: '200-399'
    alb.ingress.kubernetes.io/protocol-version: HTTP1
spec:
  rules:
  - host: nochat.io
    http:
      paths:
      - path: /api/users/login
        pathType: Exact
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/users/logout
        pathType: Exact
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/users/verify-email
        pathType: Exact
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/users/request-password-reset
        pathType: Exact
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/users/reset-password
        pathType: Exact
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/users/check-wallet
        pathType: Exact
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/users/by-wallet
        pathType: Exact
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/users/by-email
        pathType: Exact
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/users/signup
        pathType: Exact
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: nochat-users
            port:
              number: 8083
      - path: /api/ice-servers
        pathType: Exact
        backend:
          service:
            name: nochat-ice
            port:
              number: 8081
      - path: /api/contacts
        pathType: Prefix
        backend:
          service:
            name: nochat-contacts
            port:
              number: 8082
      - path: /ws/
        pathType: Prefix
        backend:
          service:
            name: nochat-signaling
            port:
              number: 8080
      - path: /health
        pathType: Exact
        backend:
          service:
            name: nochat-signaling
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nochat-web
            port:
              number: 80
