apiVersion: v1
kind: Service
metadata:
  name: nochat-signaling
  namespace: nochat
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  ports:
  - name: http-ws
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: nochat-signaling
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400 