apiVersion: v1
kind: Secret
metadata:
  name: twilio
  namespace: nochat
type: Opaque
data:
  account-sid: QUMwNDk5Yzg2OTlmNDY0YzA2NGUxNGJkMzFkYjQwMWQ3Zg==  # base64 encoded TWILIO_ACCOUNT_SID
  auth-token: MGFkM2M2N2UwODUxYTk0MTc2MGQ3NGJlMjU1MmNiY2M=  # base64 encoded TWILIO_AUTH_TOKEN 