apiVersion: v1
kind: ConfigMap
metadata:
  name: web-env
  namespace: nochat
data:
  .env: |
    REACT_APP_API_URL=wss://nochat.io/signaling
    REACT_APP_SIGNALING_SERVICE_URL=wss://nochat.io/signaling
